markdown: kramdown

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
plugins: [jekyll-paginate]
# Setup
title:               Joanna's Thoughts
tagline:             "Help!"
description:         "This is my first attempt at a blog and website. Please don't judge me."
url:                 https://luridsnapdragon.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Joanna Ortega
  url:               https://github.com/joannaortega/engl460fall2017
  email:             joanna_ortega@hotmail.com

# Custom vars
version:             1.0.0

theme: jekyll-theme-midnight
